{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "aws-s3-service.fullname" . }}
  labels:
    {{- include "aws-s3-service.labels" . | nindent 4 }}
spec:
  hosts:
    {{- range .Values.istio.gateway.hosts }}
    - {{ . | quote }}
    {{- end }}
  gateways:
    - {{ include "aws-s3-service.fullname" . }}-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ include "aws-s3-service.fullname" . }}
            port:
              number: {{ .Values.service.port }}
      timeout: {{ .Values.istio.virtualService.timeout }}
      retries:
        attempts: {{ .Values.istio.virtualService.retries.attempts }}
        perTryTimeout: {{ .Values.istio.virtualService.retries.perTryTimeout }}
        retryOn: {{ .Values.istio.virtualService.retries.retryOn }}
{{- end }}
